### ISSUE TITLE
elim.reaper leaving defunct/zombie processes

### ISSUE THREAD

**Issue by vipvan** [IBMSpectrumComputing/lsf-plugins#1]
Restarting elim.reaper does not help. 
 ps -ef |grep 511527
root     511527   4403  0 17:13 ?        00:00:00 /lsf/EVAL2/10.1/linux2.6-glibc2.3-x86_64/etc/elim.reaper
root     511529 511527  0 17:13 ?        00:00:00 [sh] <defunct>
root     511606 511527  0 17:13 ?        00:00:00 [sh] <defunct>
root     511689 511527  0 17:13 ?        00:00:00 [sh] <defunct>
root     511790 511527  0 17:14 ?        00:00:00 [sh] <defunct>
root     511865 511527  0 17:14 ?        00:00:00 [sh] <defunct>
root     512018 511527  0 17:14 ?        00:00:00 [sh] <defunct>
root     512105 511527  0 17:14 ?        00:00:00 [sh] <defunct>
root     512192 511527  0 17:14 ?        00:00:00 [sh] <defunct>
root     512279 511527  0 17:14 ?        00:00:00 [sh] <defunct>

SUSE Linux  12SP2. LSF 10.1.0.6

**Comment by adamsla** [comment]
This was resolved a while ago.  Please update to the latest version.
