### ISSUE TITLE
reaper running on hosts with no resource

### ISSUE THREAD

**Issue by vipvan** [IBMSpectrumComputing/lsf-plugins#2]
Even though the "reaper" resource is not defined for host2 in lsf cluster file, and yet the elim.reaper is running on both nodes. Would be handy to just run the reaper on nodes that have the associated resource defined, so certain hosts can be excluded from getting reaped right from cluster file configuration.

lshosts -w host1
HOST_NAME                       type       model  cpuf ncpus maxmem maxswp server RESOURCES
host1                   DELL        R740   1.0    48 385658M  3903M    Yes (viz)

lshosts -w host2
HOST_NAME                       type       model  cpuf ncpus maxmem maxswp server RESOURCES
host2                  DELL        R740   1.0    48 385658M  3903M    Yes (viz reaper)

**Comment by adamsla** [comment]
I think that this is a great feature request.  Thanks for logging it.

**Comment by adamsla** [comment]
This issue has been resolved in the develop branch:

```
git clone -b develop https://github.com/IBMSpectrumComputing/lsf-plugins.git
```

**Comment by vipvan** [comment]
Is there an option for excluding user as well besides the user group?

LSF_EXCLUDED_UGROUPS = admins
