### ISSUE TITLE
Failed to get job endTime when job exited

### ISSUE THREAD

**Issue by fengliplatform** [IBMSpectrumComputing/lsf-plugins#3]
For exit job, it seems endTime has value of 0. How to troubleshoot?

elim.reaper: Found Job (<jobid>) with endTime (0), curTime (16159xxxxx), lingerTime (900)

**Comment by adamsla** [comment]
Actually, I see some errors in the code.  That value should be an unsigned long and the format characters are just integers.  Might have something to do with it.  See below "%i" nod "%lu"

![image](https://user-images.githubusercontent.com/30323347/112151699-e740ed00-8bb7-11eb-934c-6896928c5aa7.png)

**Comment by adamsla** [comment]
So, both endTime and curTime should be defined as unsigned long's.  If it's outside of that, I would ask the LSF team why does the endTime represented as `job->endTime`; show as zero?

**Comment by adamsla** [comment]
I've updated the code.  Please have the customer test with the new version under `develop` not `master`.

**Comment by adamsla** [comment]
No feedback.
